# Generated by Django 4.2 on 2023-04-20 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vichat_app', '0004_photo_message_chat_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_history',
            name='msg_history',
        ),
        migrations.AddField(
            model_name='message',
            name='chatHistory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='vichat_app.chat_history'),
        ),
    ]
