# Generated by Django 4.2 on 2023-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichat_app', '0005_remove_chat_history_msg_history_message_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_history',
            name='roomcode',
            field=models.CharField(default='catfdog', max_length=200),
        ),
    ]
